-- MySQL Script generated by MySQL Workbench
-- Tue Jun 17 19:43:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema senac_SGA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema senac_SGA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `senac_SGA` DEFAULT CHARACTER SET utf8 ;
USE `senac_SGA` ;

-- -----------------------------------------------------
-- Table `senac_SGA`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senac_SGA`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `senha` VARCHAR(256) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `idAdmin_UNIQUE` (`idAdmin` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `senac_SGA`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senac_SGA`.`Alunos` (
  `idAlunos` INT NOT NULL AUTO_INCREMENT,
  `data_nascimento` DATE NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `Admin_idAdmin` INT NOT NULL,
  `nome` varchar(45) NOT NULL,
  PRIMARY KEY (`idAlunos`),
  UNIQUE INDEX `idAlunos_UNIQUE` (`idAlunos` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE,
  INDEX `fk_Alunos_Admin_idx` (`Admin_idAdmin` ASC) VISIBLE,
  CONSTRAINT `fk_Alunos_Admin`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `senac_SGA`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- DELETE FROM alunos
-- where idAlunos = '2';

SELECT * FROM alunos;
SELECT * FROM admin;
